### PR TITLE
feat: add customizable close button

### LINKED ISSUE #146: Custom Close Button
Would be nice to instead of having a ToastCloseButton, a ToastButton, where I could set a label and an onPressed action on it. I tried using callbacks, but it did not achieve a good result and perfomance, also, I wanted to remove the close icon, to avoid dismissing the toastification by taps on it.

### PR DESCRIPTION
**Pull request by reza00farjam**
This PR introduces a new `Widget?` property named `closeButton` to the `toastification.show` method. This addition allows developers to fully customize the default close button, providing greater flexibility and control over the toast's appearance and functionality.  

Closes #146

### CODE REVIEW

**Comment by reza00farjam** [comment]
Hi @payam-zahedi,
I’ve updated the README with an example implementation reflecting your recent refactor.

**Comment by payam-zahedi** [comment]
Thanks @reza00farjam 

I'm trying to make the API a bit more Maintainable and Customizable.
Also I'm working on example(toast builder) website that can handle this changes

**Comment by reza00farjam** [comment]
Amazing! Regarding the builder website, I think it would be great to let users add and preview their custom close button. One approach could be adding an input field or a simple code editor where they can write their custom code for the close button and see it in action within the builder.

As for the API, I suggest renaming the onTap parameter in the ToastCloseButton builder constructor to onClose for better clarity.

Let me know if these ideas align with what you had in mind or if there’s anything else I can help with to close this PR sooner. Thanks again!

@payam-zahedi

**Review by payam-zahedi — APPROVED** [review]
Thank you so much, @reza00farjam!

I've made a few changes to align your PR with our APIs to enhance the developer experience.

Looking forward to your future contributions!

**Comment by payam-zahedi** [comment]
@reza00farjam
I really liked your idea, so I’ve renamed the close callback to onClose. Feel free to check it out in the latest commit!

**Pull request merged**
