### PR TITLE
Save User's Last State in Toast Builder – Implemented State Persistence Using Drift (Issue 73)

### LINKED ISSUE #73: Save the latest state of the toast builter site - keep the user last state

### PR DESCRIPTION
**Pull request by AntonioAEMartins**
This pull request introduces state persistence in the toast builder using Hive and refines serialization for `ToastDetail` and `IconModel`. These changes enable the app to retain user customizations across sessions, ensuring a smoother and more consistent user experience.

**Key Modifications:**

1. **State Persistence with Hive:**
- Integrated Hive to store and load the user's last state of the toast builder.
- Initialized Hive in the main function and opened the `toastDetailBox` for state management.

2. **Provider Enhancements:**
- Updated `ToastDetailControllerNotifier` with `_saveState` and `_loadState` methods for saving and retrieving toast properties.
- Added error handling in `_loadState` to reset to the default state if deserialization fails.

3. **Serialization Updates:**
- **`ToastDetailSerialization` Extension:** Added `toMap` and `fromMap` methods to convert `ToastDetail` properties for Hive storage.
- **Icon Handling:** Implemented `_iconToMap` and `_iconFromMap` to handle `IconModel` serialization, including `iconData` and `color`, with a default color of white if none is provided.

4. **`IconModel` Extension:**
- Introduced `IconModelSerialization` with `toMap` and `fromMap` methods to serialize `IconModel` properties, including color conversion.

5. **UI Improvements:**
- Utilized `TextEditingController` to manage title and description input fields.
- Improved initialization and change propagation in `_ContentDesktopState` and `_ContentMobileState`.

**Benefits:**
- **Consistent User Experience:** Retains user customizations across sessions.
- **Robust State Management:** Handles errors gracefully, resetting the state if needed.
- **Flexible Customization:** Supports dynamic updates to icons and toast properties.

close #73

### CODE REVIEW

**Comment by AntonioAEMartins** [comment]
Hi @payam-zahedi,

To keep things straightforward, I've implemented this in the simplest way I could think of. I believe this approach is not only scalable but also minimizes maintenance efforts.

Let me know if you have any questions or feedback!

**Comment by payam-zahedi** [comment]
Hi @AntonioAEMartins,

Thank you so much for your hard work on this PR — great job!

I do have one concern regarding the use of the Hive package. It appears that Hive hasn't been actively maintained for some time. As an alternative, I recommend considering [Drift](https://pub.dev/packages/drift) or [ObjectBox](https://pub.dev/packages/objectbox), as both are actively maintained and provide solid support.

Thank you again for your efforts, and I look forward to your thoughts!

**Comment by AntonioAEMartins** [comment]
Thanks for you response, 

I'm going to make the necessary changes to implement ObjectBox instead of Hive.

**Comment by payam-zahedi** [comment]
That would be awesome @AntonioAEMartins 

Looking for to it

**Comment by AntonioAEMartins** [comment]
@payam-zahedi Just passing by to let you know that I'm having multiple problems while implementing Drift. I will keep trying and will update you.

**Comment by AntonioAEMartins** [comment]
Hi @payam-zahedi ,

I hope this message finds you well. I've made significant progress with my project by creating all the necessary Drift files and extending the `ToastDetail` class to serialize all fields. However, I'm encountering some challenges when integrating Drift with Riverpod.

Specifically, I'm facing compilation errors related to the dependencies when I include the following code:

```dart
final toastDetailControllerProvider =
    StateNotifierProvider<ToastDetailControllerNotifier, ToastDetail>((ref) {
  final db = ref.watch(appDatabaseProvider);
  return ToastDetailControllerNotifier(db);
});

class ToastDetailControllerNotifier extends StateNotifier<ToastDetail> {
  final AppDatabase _db;

  ToastDetailControllerNotifier(this._db) : super(ToastDetail()) {
    _loadState();
  }
}
```

When I add this code, I start receiving numerous errors from `.pub-cache` related to all dependencies. However, when I remove this code, the web app functions normally.

I’ve created a commit that includes all my changes along with this error, and I'd appreciate any insights you might have on how to resolve it. If you could take a look or suggest some ways to work around this issue, I would be very grateful.

**Comment by AntonioAEMartins** [comment]
@payam-zahedi 

I'm happy to inform you that all the errors I was encountering have been resolved. The issue stemmed from using the drift/native library, which was causing compilation problems. After consulting Drift's documentation for web support, I switched to using sqlite3.wasm for web compatibility, and everything is now working smoothly.

Thank you for your time and support. If you'd like to check out the latest commit, feel free to take a look—I'm excited about the progress!

**Comment by payam-zahedi** [comment]
Thanks @AntonioAEMartins 

I will look at new changes as soon as possible 

Sorry for late reply 

I was working on another Huge PR

**Comment by payam-zahedi** [comment]
**Copilot Summary:**

This pull request introduces significant changes to the `example` project, including the addition of a database schema for toast notifications, state management enhancements, and utility functions for data mapping. The most important changes are the initialization of the Flutter app, the creation of a database schema, and the implementation of state management for toast notifications.

### Flutter App Initialization:
* [`example/lib/main.dart`](diffhunk://#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15L14-R18): Ensured Flutter bindings are initialized before running the app.

### Database Schema and Provider:
* [`example/lib/src/database/database.dart`](diffhunk://#diff-6e4c7cbcec03366ab7112c29e184b52058d7b12e61b3bd4e396f868877bc6444R1-R101): Added a Drift database schema for toast notifications and implemented methods for CRUD operations.
* [`example/lib/src/database/database_provider.dart`](diffhunk://#diff-23eaf0a050282e6e10caf56b82ce9c89773dbe06b1aca188c1f02d91a16fd3e1R1-R8): Created a provider for the database using Riverpod.

### State Management:
* [`example/lib/src/features/home/controllers/toast_detail.dart`](diffhunk://#diff-ebe9ce5604e86631b560dca7dd1b59d48f327b0c6cbe9f6768f8c20904767076R1-R3): Enhanced the `ToastDetailControllerNotifier` to save and load state from the database, and reset state to defaults. [[1]](diffhunk://#diff-ebe9ce5604e86631b560dca7dd1b59d48f327b0c6cbe9f6768f8c20904767076R1-R3) [[2]](diffhunk://#diff-ebe9ce5604e86631b560dca7dd1b59d48f327b0c6cbe9f6768f8c20904767076L10-R193) [[3]](diffhunk://#diff-ebe9ce5604e86631b560dca7dd1b59d48f327b0c6cbe9f6768f8c20904767076R203)

### Utility Functions for Data Mapping:
* [`example/lib/src/database/utils_mapping.dart`](diffhunk://#diff-b577fd3e6881364aaf3672650c9c2205c2df02047a2e6f198c648254c57eb202R1-R227): Added utility functions to map `ToastDetail` objects to and from database schema companions.

### Icon Model Enhancements:
* [`example/lib/src/features/home/views/ui_states/icon_model.dart`](diffhunk://#diff-d1abf8519048aeae1f6929c67714ba212919501e07d5b4ba0d77c76ca1076375R11-R54): Added serialization methods to `IconModel` for converting to and from maps.
* [`example/lib/src/features/home/views/ui_states/icon_model.freezed.dart`](diffhunk://#diff-a054ff643b0942c7324e945a32e5198def413417c3e83f3b8fcfda6c161e0dd3R21-R25): Updated the `IconModel` class to include a `color` property and its corresponding copy methods. [[1]](diffhunk://#diff-a054ff643b0942c7324e945a32e5198def413417c3e83f3b8fcfda6c161e0dd3R21-R25) [[2]](diffhunk://#diff-a054ff643b0942c7324e945a32e5198def413417c3e83f3b8fcfda6c161e0dd3L32-R35) [[3]](diffhunk://#diff-a054ff643b0942c7324e945a32e5198def413417c3e83f3b8fcfda6c161e0dd3R48-R55) [[4]](diffhunk://#diff-a054ff643b0942c7324e945a32e5198def413417c3e83f3b8fcfda6c161e0dd3R66-R69) [[5]](diffhunk://#diff-a054ff643b0942c7324e945a32e5198def413417c3e83f3b8fcfda6c161e0dd3L72-R82)

**Comment by AntonioAEMartins** [comment]
Hi @payam-zahedi,

Good evening! I hope this message finds you well.

I wanted to check if there’s anything you’d like me to add or modify regarding this issue. Please let me know if there are any updates or additional details I should include.

**Comment by payam-zahedi** [comment]
@AntonioAEMartins Apologies for the delayed response.

Unfortunately, I’ve had an exceptionally busy few weeks and haven’t been able to review this PR yet. I’ll make it a priority to take a look over the weekend. Thank you for your patience.

**Comment by AntonioAEMartins** [comment]
Ok @payam-zahedi, thanks for you attention. If you need something, please let me know.

**Review by payam-zahedi — CHANGES_REQUESTED** [review]
Hi @AntonioAEMartins ,

Thank you so much for your excellent contribution! I truly appreciate the effort and thought you’ve put into this. 🙌

I’ve reviewed your PR and left several comments that I’d like you to take a look at and address when you get a chance. Below, I’ll outline an important point that I believe we need to align on to ensure everything works as expected.

#### Key Considerations

It seems that your approach in the PR focuses on updating the database whenever the user modifies the toast details from the dashboard. While this is a valid implementation, there’s a slight misalignment with our intended behavior.

- **Expected Behavior**:  
  As shown in the attached image, the saving functionality should be triggered only when the user explicitly clicks the "Save" button in the UI. This allows users to control when changes are committed to the database.

- **Initialization Flow**:  
  On app startup, we need to:  
  1. Check if any toast details are stored in the database.  
  2. If data exists, retrieve and display it.  
  3. If no data is stored, default toast details should be shown.

Once again, thank you for your great work on this. Let me know if you have any questions or need further clarification—I’d be happy to help! Looking forward to your updates. 🚀

**Comment by AntonioAEMartins** [comment]
Hey @payam-zahedi,

First of all, thank you so much for all your comments and suggestions for improvement. I've read through each one and made the necessary changes. I think the most significant update was replacing the autosave state functionality with the expected behavior—adding the ability to save to the database through the Save My Toast button.

Please let me know what you think. I'm open to make more changes if necessary.

**Comment by AntonioAEMartins** [comment]
Also, I received an email from you inviting me to become a collaborator on the Toastification repository on GitHub. I have a few questions about what my responsibilities would be, the future plans or roadmap for Toastification, and I'd like to get to know you better as well.

Do you have a Discord account or another platform we can use to talk directly?

**Review by payam-zahedi — DISMISSED** [review]
Well done @AntonioAEMartins 

The code looks really nice 

However, I think about it and change the scenario of saving and restoring the user state you can take a look at it in latest commits

**Pull request merged**
