### PR TITLE
Enhancement: [Website] Adding Color Picker Component

### PR DESCRIPTION
**Pull request by mahmoud-eslami**
### Description
This PR is related to issue #74 to add a Color picker component to change the color of the background, icons, and text.

### Tasks
- [x] Implement `Color Picker` 
- [x] Update style in `toastDetailControllerProvider`
- [x] Remove different shades on picker and add some sample colors.

### CODE REVIEW

**Comment by mahmoud-eslami** [comment]
The `Code Preview` section is functioning perfectly without any changes, so I'll update the task list and remove the code preview task.

**Comment by mahmoud-eslami** [comment]
Hey @payam-zahedi,
There are two approaches to handling the icon color in the customization panel. Due to the `toast type`, the toast icon can have different colors. So, when the user changes the color, the selected color is set as the icon's color. However, what should happen after changing the `toast type`? In this case, I can either reset the selected color and set the default color of the newly selected type as the icon's color, or simply retain the selected color. Or we can have a reset button on the **color picker**.

**Comment by mahmoud-eslami** [comment]
Hey @payam-zahedi,
New update on this feature.


https://github.com/payam-zahedi/toastification/assets/57481226/adfc05ef-7062-4f16-b267-642d6b9bcd3c

**Comment by mahmoud-eslami** [comment]
Hi @payam-zahedi,
New update on this feature.

https://github.com/payam-zahedi/toastification/assets/57481226/66840ba9-a1aa-4674-b573-faa00f87c7d9

**Comment by payam-zahedi** [comment]
Awesome

Is it ready to review

**Comment by mahmoud-eslami** [comment]
Yes, it is.

**Review by payam-zahedi — APPROVED** [review]
Thanks @mahmoud-eslami 

I really appreciate your contribution

**Comment by mahmoud-eslami** [comment]
Thank you @payam-zahedi, for granting me the opportunity to contribute to this impactful package and community.

**Pull request merged**
