### PR TITLE
Feature: optional context

### LINKED ISSUE #51: A simple toast and toastification can be without context.
1. Simple toast like this:

`toast('Hello world!');`

https://github.com/payam-zahedi/toastification/assets/59143934/67edde36-db52-4b39-bc5a-dc5e4a605cf3

2. The toastification of without context:

```
toastification.show(
	  type: ToastificationType.success,
	  style: ToastificationStyle.flat,
	  title: 'Component updates available.',
	  description: 'Component updates available.',
	  alignment: Alignment.topLeft,
	  autoCloseDuration: const Duration(seconds: 4),
	);
```

### LINKED ISSUE #76: Get.context  Unhandled Exception: No Overlay widget found.
**Describe the bug**
I am using getx.

    toastification.showCustom(
      context: context,
      autoCloseDuration: const Duration(seconds: 5),
      alignment: alignment ?? Alignment.topCenter,
      animationDuration: Duration(milliseconds: 400),
      builder: (BuildContext context, ToastificationItem holder) {
        return child;
      },
    );

showCustom need to provide a context paramete. 

I used the Get.context in getx!, But it reported wrong.

E/flutter (20377): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: No Overlay widget found.
E/flutter (20377): Some widgets require an Overlay widget ancestor for correct operation.
E/flutter (20377): The most common way to add an Overlay to an application is to include a MaterialApp, CupertinoApp or Navigator widget in the runApp() call.
E/flutter (20377): The context from which that widget was searching for an overlay was:
E/flutter (20377):   Navigator-[LabeledGlobalKey<NavigatorState>#7a7dd Key Created by default]
E/flutter (20377): #0      Overlay.of.<anonymous closure> (package:flutter/src/widgets/overlay.dart:487:9)
E/flutter (20377): #1      Overlay.of (package:flutter/src/widgets/overlay.dart:490:6)
E/flutter (20377): #2      ToastificationManager._createNotificationHolder (package:toastification/src/core/toastification_manager.dart:192:45)
E/flutter (20377): #3      ToastificationManager.showCustom (package:toastification/src/core/toastification_manager.dart:59:7)
E/flutter (20377): #4      Toastification.showCustom (package:toastification/src/core/toastification.dart:138:20)
E/flutter (20377): #5      CustomToast._commonCustom (package:share_cards_flutter/shared/util/ToastUtil.dart:94:20)
E/flutter (20377): #6      CustomToast.showStatusSuccess (package:share_cards_flutter/shared/util/ToastUtil.dart:132:5)
E/flutter (20377): #7      PictureCardController.saveImgToGallery (package:share_cards_flutter/app/modules/picture_card/controllers/picture_card_controller.dart:164:19)
E/flutter (20377): <asynchronous suspension>

My Main method is as follows：

class AppMain extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: "ShareCards",
      initialRoute: AppPages.INITIAL,
      getPages: AppPages.routes,
      theme: ThemeData.light(),
      darkTheme: ThemeData.dark(),
      themeMode: ThemeMode.system,
    );
  }
}

### LINKED ISSUE #78: Independent context
Is there any way to upgrade toastification  to remove context dependency ? 
I mean any mechanism like [fluttertoast](https://pub.dev/packages/fluttertoast) or something else .   

I can not understand why this plugin force developer to put context on show method !?!? 
also why can not use globalKey ? 
```
final navigatorKey = GlobalKey<NavigatorState>();

GetMaterialApp(
      theme: ThemeData.light(useMaterial3: false),
      debugShowCheckedModeBanner: false,
      title: 'MyApplication',
      initialRoute: '/',
      navigatorKey: navigatorKey ,
      ...
);

toastification.show(
    context: navigatorKey.currentState!.context,
    type: ToastificationType.success,
    style: ToastificationStyle.minimal,
    ....
)
```  

Error : 
```

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
No Overlay widget found.

Some widgets require an Overlay widget ancestor for correct operation.

The most common way to add an Overlay to an application is to include a MaterialApp, CupertinoApp or Navigator widget in the runApp() call.

The context from which that widget was searching for an overlay was: Navigator-[LabeledGlobalKey<NavigatorState>#fc692]
  dependencies: [HeroControllerScope, UnmanagedRestorationScope]
  state: NavigatorState#fb49e(tickers: tracking 1 ticker)
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:3       throw_
packages/flutter/src/widgets/overlay.dart 487:9                                   <fn>
packages/flutter/src/widgets/overlay.dart 489:14                                  of
packages/toastification/src/core/toastification_manager.dart 192:45               [_createNotificationHolder]
packages/toastification/src/core/toastification_manager.dart 59:7                 showCustom
packages/toastification/src/core/toastification.dart 138:19                       showCustom
packages/toastification/src/core/toastification.dart 241:12                       show
```

### PR DESCRIPTION
**Pull request by SamadiPour**
fixes #78, fixes #76, fixes #51

### CODE REVIEW

**Review by payam-zahedi — COMMENTED** [review]
Well done @SamadiPour 

Everything looks fine

**Comment by SamadiPour** [comment]
The only thing remaining is to update and clarify the new mechanism in the README.

**Comment by laterdayi** [comment]
@SamadiPour @payam-zahedi     Looking forward to updating and releasing it, a lot of people are looking forward to this feature

**Comment by laterdayi** [comment]
Do you have any plans for a merger

**Review by payam-zahedi — APPROVED** [review]
Well done @SamadiPour

Thanks for your contribution

**Pull request merged**
