### PR TITLE
Enhancement: [Website] Adding Icon Picker

### PR DESCRIPTION
**Pull request by mahmoud-eslami**
### Description

This pull request is related to issue https://github.com/payam-zahedi/toastification/issues/72, aiming to add an icon picker. This feature allows users to select a custom icon for the toast message.

### CODE REVIEW

**Comment by mahmoud-eslami** [comment]
Hi @payam-zahedi,

Just wanted to give you a quick heads up—I'm working on adding that icon picker feature. Will keep you in the loop with any updates!

**Comment by mahmoud-eslami** [comment]
The UI for the icon picker is nearly complete! Could you please take a look and share any ideas or suggestions for improvement? Let me know your thoughts.


https://github.com/payam-zahedi/toastification/assets/57481226/d8228767-d46c-43f0-ad55-8d0b54cd03cf

**Comment by payam-zahedi** [comment]
It looks really cool

I really like it 

But try to use the same Textfeild style, Textstyles and ...

**Comment by mahmoud-eslami** [comment]
Thanks for the feedback! 🙌 I will certainly use the implemented theme system in the app and will keep you informed about any new updates. ✨

**Comment by mahmoud-eslami** [comment]
Hey @payam-zahedi Could you please check new update and let me know your idea ?

https://github.com/payam-zahedi/toastification/assets/57481226/77c26f98-0fdc-4d1a-853a-5141d3edd1a4

**Review by payam-zahedi — APPROVED** [review]
Thanks for this awesome contribution @mahmoud-eslami

**Pull request merged**
